version: 2.1

orbs:
  slack: circleci/slack@5.1.1
  browser-tools: circleci/browser-tools@1.5.3

executors:
  default:
    docker:
      - image: cimg/node:lts
    working_directory: /home/circleci/todo-app

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache/yarn
      - persist_to_workspace:
          root: /home/circleci/todo-app
          paths:
            - node_modules

  type-check:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn typecheck

  lint:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn lint
  vitest:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn vitest
  e2e:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn start
      - run: yarn e2e

  build:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn build

  slack-notify:
    executor: default
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1
          mentions: "@shiro_pon"
      - slack/notify:
          event: fail
          template: basic_fail_1
          mentions: "@shiro_pon"

  storybook_screenshots:
    executor: default
    steps:
      - browser-tools/install-chrome
      - checkout
      - attach_workspace:
          at: .
      - run: yarn build-storybook
      - run: yarn storycap
      - run: yarn reg-suit

workflows:
  ci:
    jobs:
      - setup
      - type-check:
          requires:
            - setup
      - lint:
          requires:
            - setup
      - vitest:
          requires:
            - setup
      # TODO: ci 環境で msw の起動できるようにする
      - e2e:
          requires:
            - setup
      - build:
          requires:
            - setup
      - storybook_screenshots:
          requires:
            - setup
      - slack-notify:
          requires:
            - type-check
            - lint
            - vitest
            - build
          context: SLACK_ACCESS_TOKEN
