version: 2.1

orbs:
  node: circleci/node@5.3.0

executors:
  default:
    docker:
      - image: cimg/node:20.15.1

jobs:
  install_node:
    executor: default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "20.15.1"
      - run: node -v
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  test:
    executor: default
    steps:
      - checkout
      - run: yarn test

workflows:
  version: 2
  workflow:
    jobs:
      - install_node
      - test:
          requires:
            - install_node
