name: bump_version

on:
  workflow_dispatch:
    inputs:
      version:
        description: リリースを作るバージョン番号
        required: true
        default: ""

permissions:
  contents: write
  pull-requests: write

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: update version
        run: |
          yarn version --new-version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: push branch to remote
        run: |
          git checkout -b feat/bump-to-${{ github.event.inputs.version }}
          git push origin feat/bump-to-${{ github.event.inputs.version }}

      - name: create version up PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: feat/bump-to-${{ github.event.inputs.version }}
          title: "Bump to ${{ github.event.inputs.version }}"
          body: "Bump to ${{ github.event.inputs.version }}"
          base: master
env:
  GITHUB_TOKEN: ${{ secrets.PAT }}
